// Generated by CoffeeScript 1.9.2
(function() {
  var getForegroundColor;

  getForegroundColor = function(bgHexColor) {
    var b, g, r, yiq;
    bgHexColor = bgHexColor.indexOf('#') === 0 ? bgHexColor.slice(1) : bgHexColor;
    r = parseInt(bgHexColor.substr(0, 2), 16);
    g = parseInt(bgHexColor.substr(2, 2), 16);
    b = parseInt(bgHexColor.substr(4, 2), 16);
    yiq = ((r * 299) + (g * 587) + (b * 114)) / 1000;
    if (yiq >= 128) {
      return 'black';
    } else {
      return 'white';
    }
  };

  $(function() {
    var bgColor, foregroundColor;
    bgColor = '#394BA0';
    $('body').css('background-color', bgColor);
    foregroundColor = getForegroundColor(bgColor);
    return $('#text').css('color', foregroundColor);
  });

}).call(this);
