// Generated by CoffeeScript 1.9.2
(function() {
  var app, clients, express, http, io, path;

  express = require('express');

  app = express();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  path = require('path');

  app.get('/', function(req, res) {
    return res.sendFile(__dirname + "\/public\/index.html");
  });

  app.use(express["static"](path.join(__dirname, 'public')));

  clients = [];

  io.on('connection', function(socket) {
    var client, clientIp, index;
    clientIp = socket.request.connection.remoteAddress;
    console.log(clientIp);
    if (clients.indexOf(clientIp) < 0) {
      clients.push(clientIp);
    }
    console.log(clients);
    socket.join(clientIp);
    socket.on('disconnect', function() {
      var index;
      console.log('user disconnected');
      index = clients.indexOf(clientIp);
      return clients.splice(index, 1);
    });
    socket.on('set-background', function(hexColor) {
      return io.to(clientIp).emit('update-background', hexColor);
    });
    if (clients.length > 1) {
      index = clients.indexOf(clientIp);
      client = clients[(index + 1) % clients.length];
      console.log('Client: ' + client);
      return io.to(client).emit('update-background', '#ff33cc');
    }
  });

  http.listen(3000, function() {
    return console.log('listening on *:3000');
  });

}).call(this);
