// Generated by CoffeeScript 1.9.2
(function() {
  var app, express, http, io, path;

  express = require('express');

  app = express();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  path = require('path');

  app.use(express["static"](path.join(__dirname, 'public')));

  app.get('/', function(req, res) {
    return res.sendFile(__dirname + "\/public\/index.html");
  });

  io.on('connection', function(socket) {
    var clientIp;
    clientIp = socket.request.connection.remoteAddress;
    console.log(clientIp);
    socket.join(clientIp);
    socket.on('disconnect', function() {
      return console.log('user disconnected');
    });
    return socket.on('set-background', function(hexColor) {
      return io.to(clientIp).emit('update-background', hexColor);
    });
  });

  http.listen(3000, function() {
    return console.log('listening on *:3000');
  });

}).call(this);
